Repository wuhan2020/data-sync, pull requests merged in 2020-02, with the labels that each got.

#41 Doc: fix typo in README
  README.md
Labels: area/document

#44 refactor: add index file and id to fe data
  app/schema/table.ts
  app/schema/table_clinic.ts
  app/schema/table_donation.ts
  app/schema/table_hospital.ts
  app/schema/table_logistical.ts
  app/schema/table_travel_hotel.ts
  app/service/shimo.ts
  test/app/service/data_format.test.ts
  test/app/service/location.test.ts
  test/app/service/utility.test.ts
Labels: kind/enhancement

#45 fix: item should not include not
  app/schema/table.ts
Labels: kind/bug

#49 fix: replace all bug fix
  app/service/data_format.ts
  test/app/service/data_format.test.ts
Labels: kind/bug

#58 refactor: refactor donation and logistical table
  app/schema/table_donation.ts
  app/schema/table_logistical.ts
  app/service/shimo.ts
Labels: kind/enhancement

#64 refactor: replace null value with empty string
  app/service/data_format.ts
Labels: kind/enhancement

#66 feature: add enterprise donation table
  app/schema/table_enterprise_donation.ts
  app/service/shimo.ts
  config/config.default.ts
Labels: kind/feature

#67 refactor(service:data-format): reactor format method and add logger
  .editorconfig
  app/service/data_format.ts
Labels: kind/enhancement, pull/approved

#61 fix: change the '@octokit/rest' import statement
  .gitignore
  app/service/github.ts
  lint-staged.config.js
  package.json
Labels: kind/bug, pull/approved

#68 feature: add factory data type
  app/schema/table.ts
  app/schema/table_factory.ts
  app/service/data_format.ts
  app/service/shimo.ts
  config/config.default.ts
  test/app/service/data_format.test.ts
Labels: kind/feature

#70 feature: add qiniu client
  app/service/qiniu.ts
  app/service/shimo.ts
  config/config.default.ts
  package.json
  typings/app/service/index.d.ts
Labels: kind/feature

#74 refactor: change to a more stable api
  app/external_api/api_isaaclin.ts
  app/service/github.ts
  app/service/qiniu.ts
Labels: kind/enhancement

#78 feat: update error info to database
  app/service/data_format.ts
  app/service/shimo.ts
  test/app/service/data_format.test.ts
Labels: kind/bug

#73 完成医疗人员指定酒店解析代码
  app/schema/table_doctor_hotel.ts
  config/config.default.ts
  test/app/service/location.test.ts
  test/app/service/utility.test.ts
Labels: pull/approved

#79 fix: doctor hotel schema fix
  app/schema/table_doctor_hotel.ts
Labels: kind/bug

#81 refactor(schema:patient): add new province
  app/schema/table_doctor_hotel.ts
  app/schema/table_patient_detail.ts
Labels: kind/enhancement

#75 Plugin datacache
  app/controller/home.ts
  app/service/location.ts
  config/config.default.ts
  config/plugin.ts
  lib/plugin/egg-datacache/app.ts
  lib/plugin/egg-datacache/config/config.default.ts
  lib/plugin/egg-datacache/extend/Cache.ts
  lib/plugin/egg-datacache/extend/datacache.ts
  lib/plugin/egg-datacache/index.d.ts
  lib/plugin/egg-datacache/package.json
  test/app/controller/home.test.ts
  test/app/plugin/data-cache.test.ts
  typings/app/controller/index.d.ts
Labels: pull/approved

#90 refactor(shema:logistical): refactor schema to add more data
  app/schema/table_logistical.ts
Labels: kind/enhancement
