Repository wuhan2020/data-sync, pull requests merged in 2020-01, with the labels that each got.

#14 doc: add uml file real time render
  README.md
  static/architecture.uml
Labels: area/document

#16 refactor: no empty commit
  app/service/github.ts
Labels: kind/enhancement

#17 feature: add type
  app/schema/table.ts
  app/schema/table_hospital.ts
  app/schema/table_hotel.ts
  app/schema/table_logistical.ts
  app/service/github.ts
Labels: kind/feature

#18 feature: add clinic table
  app/schema/table_clinic.ts
  config/config.default.ts
Labels: kind/feature

#19 feature: add donation table
  app/schema/table_donation.ts
  config/config.default.ts
Labels: kind/feature

#21 doc: add architecture
  ARCHITECTURE.md
Labels: area/document

#24 refactor: remove prefix
  app/schema/table.ts
  app/schema/table_clinic.ts
  app/schema/table_donation.ts
  app/schema/table_hospital.ts
  app/schema/table_hotel.ts
  app/schema/table_logistical.ts
  app/service/github.ts
Labels: kind/enhancement

#25 doc: update arch
  ARCHITECTURE.md
Labels: area/document

#26 refactor: split service
  app/schedule/update_shimo.ts
  app/service/github.ts
  app/service/shimo.ts
  typings/app/service/index.d.ts
Labels: kind/enhancement

#28 refactor: change-data-structure
  ARCHITECTURE.md
  app/schema/table.ts
  app/schema/table_clinic.ts
  app/schema/table_donation.ts
  app/schema/table_hospital.ts
  app/schema/table_hotel.ts
  app/schema/table_logistical.ts
  app/service/data_format.ts
  app/service/shimo.ts
  config/config.default.ts
  package.json
  typings/app/service/index.d.ts
Labels: kind/enhancement

#31 feature: add data type support
  app/service/data_format.ts
  test/app/service/data_format.test.ts
Labels: kind/feature

#33 feature: support gitee
  app/component/gitee-client.ts
  app/service/gitee.ts
  app/service/shimo.ts
  config/config.default.ts
  package.json
  tslint.json
  typings/app/service/index.d.ts
Labels: kind/feature, pull/approved

#34 refactor: add bool type
  app/controller/home.ts
  app/schema/table.ts
  app/service/Test.ts
  app/service/data_format.ts
  test/app/controller/home.test.ts
  test/app/service/Test.test.ts
  typings/app/controller/index.d.ts
  typings/app/service/index.d.ts
Labels: kind/enhancement, pull/approved

#36 refactor: Modify hospital
  app/router.ts
  app/schema/table.ts
  app/schema/table_clinic.ts
  app/schema/table_donation.ts
  app/schema/table_hospital.ts
  app/schema/table_hotel.ts
  app/schema/table_logistical.ts
  app/schema/table_travel_hotel.ts
  app/service/data_format.ts
  app/service/shimo.ts
  config/config.default.ts
Labels: kind/enhancement

#39 feature: add front end parser
  app/schema/table.ts
  app/schema/table_clinic.ts
  app/schema/table_donation.ts
  app/schema/table_hospital.ts
  app/schema/table_logistical.ts
  app/schema/table_travel_hotel.ts
  app/service/data_format.ts
  app/service/shimo.ts
  package.json
Labels: kind/feature

#40 fix: add contacts to hospital
  app/schema/table_hospital.ts
Labels: kind/bug
